[package]
name = "pipe-pegger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
core_affinity = "0.8.3"
nix = { version = "0.30.1", features = ["fs"] }
